title: "Carlos Teixeira"
author: "Carlos Eduardo Rangel Teixeira"
description: "Made with <b style=\"color: #f45;\">&lt;3</b> and Hate"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "portifolio.html", title:"Portifólio"}
  - {file: "README.md"}
  - {title: "Linkedin", link: "https://www.linkedin.com/in/carlos-teixeira-582790154/"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:certeixeira@outlook.com"}
  - {title: Github, icon: github, url: "https://github.com/certeixeira"}
  - {title: Subscribe, icon: twitter, url: "https://twitter.com/caraiocarlo"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
